#!/bin/bash

set -x

IFS=: read REPO_NAME REPO_TAG <<< "$IMAGE_NAME"

for CUDA_VERSION in 11.2 10.2; do
    docker build --build-arg CUDA_VERSION=$CUDA_VERSION -t $REPO_NAME:$CUDA_VERSION .
done

docker tag $REPO_NAME:$CUDA_VERSION $REPO_NAME:latest

